### PR TITLE
Make advanced search result export v2 compatible with entry import v2

### PR DESCRIPTION
**Pull request by syucream**
The advanced search result export v1 outputs entry import v1 compatible data format, but v2 is not so. Its because the v2 export data format is same as v1's ...

### CODE REVIEW

**Review by hinashi — COMMENTED** [review]
The format of entry, named_entry, group, role, and date attributes was different from entry export.
Therefore the import will fail.

### advanced search result export
```
  - attrs:
    - name: entry
      value:
        entity: null
        name: ''
    - name: named_entry
      value:
        ? ''
        : entity: null
          name: ''
    - name: group
      value: ''
    - name: role
      value: ''
    - name: date
      value: '2023-01-01'
```
### entry export
```
  - attrs:
    - name: entry
      value: null
    - name: named_entry
      value: {}
    - name: group
      value: null
    - name: role
      value: null
    - name: date
      value: 2023-01-01
```

**Comment by syucream** [comment]
Fixed how to handle no-value cases. How about that?

**Review by hinashi — APPROVED** [review]
LGTM! thanks for fixing.

**Review by userlocalhost — APPROVED** [review]
Thank you very much for this important work 👍

**Pull request merged**
