### PR TITLE
Added a new feature of Role

### LINKED ISSUE #462: New feature Role
## Background and Problems
Now, AirOne has function that enables to set ACL to individual information (e.g. Entity, Entry and each Attributes of them) for both Users and Groups. But this design that User and Group stick with authorization mechanism has following problems. The most biggest one is transferring settings. It's hard to transfer ACL to other User/Group. When access policy is changed, ACL setting must be transferred to others. But it's hard to do that for now.

## Solution
A feature `Role` that enables to attach and detach ACL policy to Users and Groups would solve this problem.

### PR DESCRIPTION
**Pull request by userlocalhost**
Close: https://github.com/dmm-com/airone/issues/462

This PR has new application function "Role" that enable to set ACL for individual ACLBase object.

### Update DB schema
This PR requires to alter DB schema by following SQL.
```sql
--
-- Table structure for table `role_role`
--

DROP TABLE IF EXISTS `role_role`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `role_role` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `is_active` tinyint(1) NOT NULL,
  `description` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `role_role`
--

LOCK TABLES `role_role` WRITE;
/*!40000 ALTER TABLE `role_role` DISABLE KEYS */;
/*!40000 ALTER TABLE `role_role` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `role_role_admin_groups`
--

DROP TABLE IF EXISTS `role_role_admin_groups`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `role_role_admin_groups` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `role_id` bigint(20) NOT NULL,
  `group_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `role_role_admin_groups_role_id_group_id_55ff285a_uniq` (`role_id`,`group_id`),
  KEY `role_role_admin_grou_group_id_38d9ee1c_fk_group_gro` (`group_id`),
  CONSTRAINT `role_role_admin_grou_group_id_38d9ee1c_fk_group_gro` FOREIGN KEY (`group_id`) REFERENCES `group_group` (`group_ptr_id`),
  CONSTRAINT `role_role_admin_groups_role_id_8e8bed42_fk_role_role_id` FOREIGN KEY (`role_id`) REFERENCES `role_role` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `role_role_admin_groups`
--

LOCK TABLES `role_role_admin_groups` WRITE;
/*!40000 ALTER TABLE `role_role_admin_groups` DISABLE KEYS */;
/*!40000 ALTER TABLE `role_role_admin_groups` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `role_role_admin_users`
--

DROP TABLE IF EXISTS `role_role_admin_users`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `role_role_admin_users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `role_id` bigint(20) NOT NULL,
  `user_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `role_role_admin_users_role_id_user_id_61dfed2f_uniq` (`role_id`,`user_id`),
  KEY `role_role_admin_users_user_id_630ce128_fk_user_user_user_ptr_id` (`user_id`),
  CONSTRAINT `role_role_admin_users_role_id_770bf5a9_fk_role_role_id` FOREIGN KEY (`role_id`) REFERENCES `role_role` (`id`),
  CONSTRAINT `role_role_admin_users_user_id_630ce128_fk_user_user_user_ptr_id` FOREIGN KEY (`user_id`) REFERENCES `user_user` (`user_ptr_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `role_role_admin_users`
--

LOCK TABLES `role_role_admin_users` WRITE;
/*!40000 ALTER TABLE `role_role_admin_users` DISABLE KEYS */;
/*!40000 ALTER TABLE `role_role_admin_users` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `role_role_groups`
--

DROP TABLE IF EXISTS `role_role_groups`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `role_role_groups` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `role_id` bigint(20) NOT NULL,
  `group_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `role_role_groups_role_id_group_id_2e4c7938_uniq` (`role_id`,`group_id`),
  KEY `role_role_groups_group_id_93b5a4d5_fk_group_group_group_ptr_id` (`group_id`),
  CONSTRAINT `role_role_groups_group_id_93b5a4d5_fk_group_group_group_ptr_id` FOREIGN KEY (`group_id`) REFERENCES `group_group` (`group_ptr_id`),
  CONSTRAINT `role_role_groups_role_id_85474b43_fk_role_role_id` FOREIGN KEY (`role_id`) REFERENCES `role_role` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `role_role_groups`
--

LOCK TABLES `role_role_groups` WRITE;
/*!40000 ALTER TABLE `role_role_groups` DISABLE KEYS */;
/*!40000 ALTER TABLE `role_role_groups` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `role_role_permissions`
--

DROP TABLE IF EXISTS `role_role_permissions`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `role_role_permissions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `role_id` bigint(20) NOT NULL,
  `permission_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `role_role_permissions_role_id_permission_id_54029e74_uniq` (`role_id`,`permission_id`),
  KEY `role_role_permission_permission_id_aa92d03f_fk_auth_perm` (`permission_id`),
  CONSTRAINT `role_role_permission_permission_id_aa92d03f_fk_auth_perm` FOREIGN KEY (`permission_id`) REFERENCES `auth_permission` (`id`),
  CONSTRAINT `role_role_permissions_role_id_049ae5f3_fk_role_role_id` FOREIGN KEY (`role_id`) REFERENCES `role_role` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `role_role_permissions`
--

LOCK TABLES `role_role_permissions` WRITE;
/*!40000 ALTER TABLE `role_role_permissions` DISABLE KEYS */;
/*!40000 ALTER TABLE `role_role_permissions` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `role_role_users`
--

DROP TABLE IF EXISTS `role_role_users`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `role_role_users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `role_id` bigint(20) NOT NULL,
  `user_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `role_role_users_role_id_user_id_ea410a6a_uniq` (`role_id`,`user_id`),
  KEY `role_role_users_user_id_4dc83a47_fk_user_user_user_ptr_id` (`user_id`),
  CONSTRAINT `role_role_users_role_id_0b5edf61_fk_role_role_id` FOREIGN KEY (`role_id`) REFERENCES `role_role` (`id`),
  CONSTRAINT `role_role_users_user_id_4dc83a47_fk_user_user_user_ptr_id` FOREIGN KEY (`user_id`) REFERENCES `user_user` (`user_ptr_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `role_role_users`
--

LOCK TABLES `role_role_users` WRITE;
/*!40000 ALTER TABLE `role_role_users` DISABLE KEYS */;
/*!40000 ALTER TABLE `role_role_users` ENABLE KEYS */;
UNLOCK TABLES;
```

### CODE REVIEW

**Review by hinashi — COMMENTED** [review]
(memo)
- The inheritance source of the model of group and role is the same.
So it is an error trying to create an entry with the same name.
- If enter in narrow down, the values will be duplicated.
- There is an issue where you can create a role without administrator privileges.
- There is an issue where you can make a roll without a name.

- main.js is included in commit

**Comment by userlocalhost** [comment]
> * main.js is included in commit
> * There is an issue where you can make a roll without a name.

I've done above (2/5) problem.
スクリーンショット 2022-04-06 17 49 36

**Comment by userlocalhost** [comment]
> * The inheritance source of the model of group and role is the same.
>   So it is an error trying to create an entry with the same name.

I've done to fix above problem by [9686c0d](https://github.com/dmm-com/airone/pull/463/commits/9686c0d64afcc30f719001270b81f79afe7f4ef4) (3/5 has been finished)

**Comment by userlocalhost** [comment]
> * If enter in narrow down, the values will be duplicated.
> * There is an issue where you can make a roll without a name.

Fixed above problems by previous two commits.
スクリーンショット 2022-04-07 12 25 15

**Comment by userlocalhost** [comment]
## rest of work
* Add new attribute and feature that describes policy and explanation of creating role.

**Comment by userlocalhost** [comment]
https://github.com/dmm-com/airone/pull/463#issuecomment-1094502402 is done by https://github.com/dmm-com/airone/pull/463/commits/7a2cc50fbdb575753ecfac62ca9233cc9915fee3

**Review by hinashi — APPROVED** [review]
LGTM!

**Pull request merged**
