### PR TITLE
Fix some React warnings again

### PR DESCRIPTION
**Pull request by syucream**
Fix some warnings:
- Replace deprecated features
- Specify missing key's
- Make some input elements controllable
- Fix TableBody not to omit a row (see https://stackoverflow.com/questions/39914455/react-validatedomnesting-text-cannot-appear-as-a-child-of-tr)

### CODE REVIEW

**Comment by hinashi** [comment]
After building, the following warning message was output.
`export 'alpha' (imported as 'alpha') was not found in '@material-ui/core/styles'`

**Comment by userlocalhost** [comment]
Following was execution result of `npm run build` in my environment.
```
> airone@1.0.0 build
> npm run build:development


> airone@1.0.0 build:development
> webpack build --mode development

asset new-ui.js 2.49 MiB [emitted] (name: index)
orphan modules 761 KiB [orphan] 396 modules
runtime modules 1.13 KiB 5 modules
cacheable modules 1.89 MiB
  modules by path ./node_modules/ 1.78 MiB 184 modules
  modules by path ./frontend/src/ 106 KiB
    modules by path ./frontend/src/pages/*.js 56.5 KiB 16 modules
    modules by path ./frontend/src/components/ 41.1 KiB 13 modules
    modules by path ./frontend/src/utils/*.js 5.1 KiB
      ./frontend/src/utils/AironeAPIClient.js 4.82 KiB [built] [code generated]
      ./frontend/src/utils/Constants.js 89 bytes [built] [code generated]
      ./frontend/src/utils/DjangoUtils.js 202 bytes [built] [code generated]
    ./frontend/src/App.js 3.7 KiB [built] [code generated]

WARNING in ./frontend/src/components/Header.js 38:23-28
export 'alpha' (imported as 'alpha') was not found in '@material-ui/core/styles' (possible exports: MuiThemeProvider, ServerStyleSheets, StylesProvider, ThemeProvider, createGenerateClassName, createMuiTheme, createStyles, darken, decomposeColor, duration, easing, emphasize, fade, getContrastRatio, getLuminance, hexToRgb, hslToRgb, jssPreset, lighten, makeStyles, recomposeColor, responsiveFontSizes, rgbToHex, styled, unstable_createMuiStrictModeTheme, useTheme, withStyles, withTheme)
 @ ./frontend/src/App.js 6:0-41 31:38-44

WARNING in ./frontend/src/components/Header.js 40:25-30
export 'alpha' (imported as 'alpha') was not found in '@material-ui/core/styles' (possible exports: MuiThemeProvider, ServerStyleSheets, StylesProvider, ThemeProvider, createGenerateClassName, createMuiTheme, createStyles, darken, decomposeColor, duration, easing, emphasize, fade, getContrastRatio, getLuminance, hexToRgb, hslToRgb, jssPreset, lighten, makeStyles, recomposeColor, responsiveFontSizes, rgbToHex, styled, unstable_createMuiStrictModeTheme, useTheme, withStyles, withTheme)
 @ ./frontend/src/App.js 6:0-41 31:38-44

webpack 5.36.2 compiled with 2 warnings in 4802 ms
```

**Review by userlocalhost — COMMENTED** [review]
Following is the execution result of `npm run build` in my environment.
```
> airone@1.0.0 build
> npm run build:development


> airone@1.0.0 build:development
> webpack build --mode development

asset new-ui.js 2.49 MiB [emitted] (name: index)
orphan modules 761 KiB [orphan] 396 modules
runtime modules 1.13 KiB 5 modules
cacheable modules 1.89 MiB
  modules by path ./node_modules/ 1.78 MiB 184 modules
  modules by path ./frontend/src/ 106 KiB
    modules by path ./frontend/src/pages/*.js 56.5 KiB 16 modules
    modules by path ./frontend/src/components/ 41.1 KiB 13 modules
    modules by path ./frontend/src/utils/*.js 5.1 KiB
      ./frontend/src/utils/AironeAPIClient.js 4.82 KiB [built] [code generated]
      ./frontend/src/utils/Constants.js 89 bytes [built] [code generated]
      ./frontend/src/utils/DjangoUtils.js 202 bytes [built] [code generated]
    ./frontend/src/App.js 3.7 KiB [built] [code generated]

WARNING in ./frontend/src/components/Header.js 38:23-28
export 'alpha' (imported as 'alpha') was not found in '@material-ui/core/styles' (possible exports: MuiThemeProvider, ServerStyleSheets, StylesProvider, ThemeProvider, createGenerateClassName, createMuiTheme, createStyles, darken, decomposeColor, duration, easing, emphasize, fade, getContrastRatio, getLuminance, hexToRgb, hslToRgb, jssPreset, lighten, makeStyles, recomposeColor, responsiveFontSizes, rgbToHex, styled, unstable_createMuiStrictModeTheme, useTheme, withStyles, withTheme)
 @ ./frontend/src/App.js 6:0-41 31:38-44

WARNING in ./frontend/src/components/Header.js 40:25-30
export 'alpha' (imported as 'alpha') was not found in '@material-ui/core/styles' (possible exports: MuiThemeProvider, ServerStyleSheets, StylesProvider, ThemeProvider, createGenerateClassName, createMuiTheme, createStyles, darken, decomposeColor, duration, easing, emphasize, fade, getContrastRatio, getLuminance, hexToRgb, hslToRgb, jssPreset, lighten, makeStyles, recomposeColor, responsiveFontSizes, rgbToHex, styled, unstable_createMuiStrictModeTheme, useTheme, withStyles, withTheme)
 @ ./frontend/src/App.js 6:0-41 31:38-44

webpack 5.36.2 compiled with 2 warnings in 4802 ms
```

**Comment by syucream** [comment]
@userlocalhost @hinashi could you check it again? 🙏

**Comment by hinashi** [comment]
@syucream 
It was still an error in my local environment.
It was solved by upgrading @material-ui/core 4.11.2 to 4.12.3.
I think you need to update package.json.

**Comment by syucream** [comment]
@hinashi I did it, how about this?

**Comment by userlocalhost** [comment]
I confirmed I could run `npm run build` as below

**Review by hinashi — APPROVED** [review]
LGTM!

**Pull request merged**
