### PR TITLE
Make the frontend a module for customview

### PR DESCRIPTION
**Pull request by syucream**
Current custom view is being in chaos ...

- No official API, so some developers will call various exported variables/functions directly. So custom views will be broken easily with this repo's changes.
- No node module management for custom views. Mostly it requires to install additional modules in "this" repo.
- It should require filesystem hack to install custom views, e.g. put their custom views in `frontend/src/customview/...`, a non-scalable way ...

So I wanna propose a smarter integration way between core (this repo) and custom views. Just providing this frontend implementations as a node module, then make developers to extend it theirselves. Thats like class-extension in some object-oriented languages, `class MyCustomView extends PagodaCore { ...`.
Its an example customview project to extend that with a simple React components.
https://github.com/syucream/pagoda-customview-example

### CODE REVIEW

**Comment by syucream** [comment]
Separated a large, independent improvement part as another PR:
https://github.com/dmm-com/pagoda/pull/1318

**Comment by syucream** [comment]
Now it works fine with my super simple sample project! https://github.com/syucream/pagoda-customview-example

image

**Comment by syucream** [comment]
And also I've added a workflow to auto-publish the `pagoda-core` npm module, triggered on a new release tag named `pagoda-core-x.y.z`.

**Review by userlocalhost — APPROVED** [review]
How excellent this is !!

**Comment by syucream** [comment]
Now my experimental module is available on https://github.com/users/syucream/packages/npm/pagoda-core/versions 🎉 
I've granted @userlocalhost and @hinashi admin permissions!

**Review by hinashi — APPROVED** [review]
LGTM!

**Pull request merged**
