### PR TITLE
API request without token results in exception error

### LINKED ISSUE #58: API request without token results in exception error
Exception error is output because there is no user authentication validation in some APIs.
e.g.
```
curl -X POST 'http://(AirOneURL)/api/v1/entry' \
-H 'Authorization: Token xxxxx' \
-H "Content-type: application/json" \
-d '{ "entity": "TestEntity", "name": "TestEntry", "attrs":{}}'
```
Enter an incorrect value for Token.

### PR DESCRIPTION
**Pull request by hinashi**
close: https://github.com/dmm-com/airone/issues/58

### CODE REVIEW

**Review by userlocalhost — COMMENTED** [review]
Thank you for issuing and giving a PR.
But the validation processing of authentication token looks like to be worked properly to me. The below was execution result on my environment. When I send a request to AirOne API endpoint with entering an incorrect toekn, then it returns HTTP401 (Unauthoried).
```
user@localhost:~$ curl --verbose -X POST "http://127.0.0.1:8080/api/v1/entry" \
> -H "Authorization: Token xxxxx" \
> -H "Content-type: application/json" \
> -d "{ "entity": "TestEntity", "name": "TestEntry", "attrs":{}}"
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> POST /api/v1/entry HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.58.0
> Accept: */*
> Authorization: Token xxxxx
> Content-type: application/json
> Content-Length: 48
> 
* upload completely sent off: 48 out of 48 bytes
* HTTP 1.0, assume close after body
< HTTP/1.0 401 Unauthorized
< Date: Tue, 22 Dec 2020 02:11:41 GMT
< Server: WSGIServer/0.2 CPython/3.6.9
< Content-Type: application/json
< WWW-Authenticate: Token
< Vary: Accept
< Allow: GET, POST, DELETE, HEAD, OPTIONS
< X-Frame-Options: SAMEORIGIN
< Content-Length: 27
< 
* Closing connection 0
{"detail":"Invalid token."}user@localhost:~$
```

Could you please tell me more detail about reproduction procedure and what error was happened?

**Comment by hinashi** [comment]
Thank you for checking.
Without the Authorization header, authentication will pass and an exception error will occur.
Because the authenticate_credentials of AironeTokenAuth is not called.
https://github.com/dmm-com/airone/blob/632b0d18475f4228ee37e22b75b5c8663794e5ef/api_v1/auth.py#L10

Since the default of permission_classes is AllowAny, it could be executed without authentication.
Change to require authentication in IsAuthenticated.

**Review by userlocalhost — COMMENTED** [review]
Thank you very much for fixing. It's much better now!
You may want to add a test whether response status code is 401 after sending a request without 'authentication' header.

**Review by userlocalhost — APPROVED** [review]
LGTM!

**Comment by takano32** [comment]
LGTM

**Review by takano32 — APPROVED** [review]

**Pull request merged**
