### PR TITLE
Reimplement prototype AirOne WebUI in React

### PR DESCRIPTION
**Pull request by syucream**
It re-implements AirOne WebUI in React.

# Background

Current WebUI mixes Django template and jQuery. It works fine but has some issues:

- There're some more modern technical stacks now, like React
- Each components are not so testable, maintainable.
- We have some duplicated code on both Django and jQuery (e.g. advanced search)
- etc...

# Reactize

I try to reimplement it in React with Material-UI. It helps

- To realize SPA with React components
- To use predefined styles in Material-UI
- To simplify technical stacks on UI part.

## How to build

```sh
$ npm install
$ npm run build
```

## React components

```
frontend/
└── src
    ├── App.js
    ├── components: reusable React components
    ├── pages: React based pages 
    └── utils: util functions/classes
```
## Backend APIs

We additionally provide some REST APIs for React components to render UI dynamically. It has `.../api/v2/...` parts on the URLs to express that the endpoints are separated from existing `/api/v1/` and its not for jQuery based UI.

- https://github.com/dmm-com/airone/issues/160
- https://github.com/dmm-com/airone/issues/161

### CODE REVIEW

**Comment by syucream** [comment]
# current status

## pages

### entities

image

### entries

image

## recent updates

- Install [React Router](https://reactrouter.com/) to perform routing on some pages
- Call `get_entities` and `get_entries` APIs via Fetch API
- Try some essential Material UI components, like `Table`, `Breadcrumbs`, `Menu`, etc

## considerations

- Use TypeScript or not?
  - Webpack passes to build JS files with some runtime errors. Its so hard to find a cause on browser because built .js is minified.
  - Type system helps us.
- What components we put on fundamental pages like top page?
  - Links to users and groups are really necessary for the current usage?
  - etc...

**Comment by syucream** [comment]
# current status

I changed to purely re-implement current UI in React.

## pages

### dashboard

image

### entities

image


### entries

image

image

### advanced search

image

### search result

image


## recent updates

- Tried to perform POST request with CSRF token
- Applied some rich material-ui components

## considerations

- Try form and submitting
- testing

**Comment by syucream** [comment]
# current status

## pages(only updates)

### advanced search

image

### advanced search result

image

### users

image

### user editor

image

### user password editor

image

### groups

image

### group editor

image

### operation history

image

### ACL

image

**Review by takano32 — APPROVED** [review]
LGTM

**Pull request merged**
